version: '4.5.4-TUNNELVISION+AppVeyor.{build}'
os: Windows Server 2012
environment:
    JDK_SOURCE_ROOT : C:\Program Files\Java\jdk1.8.0
build_script:
  - mvn compile -q --batch-mode 
test_script:
  - mvn install -q --batch-mode
  - ps : | 
        $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
        $xmlPath = join-path $env:APPVEYOR_BUILD_FOLDER tool\target\surefire-reports
        $wc = New-Object 'System.Net.WebClient'
        get-childitem $xmlPath | % { $wc.UploadFile($url, $_)}
